type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start 0:
      type: "start"
      transitions:
        unconditional:
        - "S3 Load - Student records"
      skipped: false
      parameters:
        componentName: "Start 0"
    S3 Load - Student records:
      type: "s3-load"
      skipped: false
      parameters:
        componentName: "S3 Load - Student records"
        stage: "Stage_AWS"
        pattern: ".*"
        encryption: "None"
        warehouse: "COMPUTE_WH"
        database: "DEMO_DB"
        schema: "PUBLIC"
        targetTable: "STUDENTRECORDS"
        loadColumns:
        - "RECORDID"
        - "STUDENTNAME"
        - "SUBJECT"
        - "MARKS"
        - "YEAR"
        format: "[Custom]"
        fileType: "CSV"
        compression: "AUTO"
        recordDelimiter: ""
        fieldDelimiter: ","
        skipHeader: "1"
        skipBlankLines: "False"
        dateFormat: ""
        timeFormat: ""
        timestampFormat: ""
        escape: ""
        escapeUnenclosedField: ""
        trimSpace: "False"
        fieldOptionallyEnclosed: ""
        nullIf:
        errorOnColumnCountMismatch: "False"
        emptyFieldAsNull: "True"
        replaceInvalidCharacters: "False"
        encodingType: ""
        onError: "Abort Statement"
        sizeLimitB: ""
        purgeFiles: "False"
        truncateColumns: "False"
        forceLoad: "True"
        metadataFields:
design:
  components:
    Start 0:
      position:
        x: 0
        "y": 0
      tempMetlId: 1082
    S3 Load - Student records:
      position:
        x: 131
        "y": 0
      tempMetlId: 1086
