type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start 0:
      type: "start"
      transitions:
        unconditional:
        - "S3 Load 0"
      skipped: false
      parameters:
        componentName: "Start 0"
    S3 Load 0:
      type: "s3-load"
      skipped: false
      parameters:
        componentName: "S3 Load 0"
        stage: "S3prjrenbanking_SnowMY_BANKING"
        pattern: "${EV_BANK_TRANS_DIRECTORY}/${EV_BANK_TRANS_FILENAME}.csv"
        encryption: "None"
        warehouse: "COMPUTE_WH"
        database: "DEMO_DB"
        schema: "MY_BANKING"
        targetTable: "TRANSACTIONS"
        loadColumns:
        - "TRANS_ID"
        - "ACCOUNT_ID"
        - "TRANS_DATE"
        - "TYPE"
        - "OPERATION"
        - "AMOUNT"
        - "BALANCE"
        - "PURPOSE"
        - "BANK"
        - "ACCOUNT_PARTNER_ID"
        format: "[Custom]"
        fileType: "CSV"
        compression: "AUTO"
        recordDelimiter: ""
        fieldDelimiter: ","
        skipHeader: "1"
        skipBlankLines: "False"
        dateFormat: ""
        timeFormat: ""
        timestampFormat: ""
        escape: ""
        escapeUnenclosedField: ""
        trimSpace: "False"
        fieldOptionallyEnclosed: ""
        nullIf:
        errorOnColumnCountMismatch: "False"
        emptyFieldAsNull: "True"
        replaceInvalidCharacters: "False"
        encodingType: ""
        onError: "Abort Statement"
        sizeLimitB: ""
        purgeFiles: "False"
        truncateColumns: "False"
        forceLoad: "True"
        metadataFields:
design:
  components:
    Start 0:
      position:
        x: 0
        "y": 0
      tempMetlId: 3397
    S3 Load 0:
      position:
        x: 272
        "y": 0
      tempMetlId: 3398
