type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start 0:
      type: "start"
      transitions:
        unconditional:
        - "Loop Iterator 0"
      skipped: false
      parameters:
        componentName: "Start 0"
    SQL Script 0:
      type: "sql-script"
      skipped: false
      parameters:
        componentName: "SQL Script 0"
        sqlScript: "CREATE OR REPLACE TABLE TXNS_${EV_YEAR}(\ntrans_id INT,\t\naccount_id\t\
          INT,\ntrans_date\tDATE,\nType\tVARCHAR(30),\noperation\tVARCHAR(40),\namount\t\
          INT,\nbalance\tFLOAT,\nPurpose\tVARCHAR(40),\nbank\tVARCHAR(45),\naccount_partner_id\
          \ INT);"
    Loop Iterator 0:
      type: "loop-iterator"
      transitions:
        success:
        - "Loop Iterator 1"
      iterationTarget: "SQL Script 0"
      skipped: false
      parameters:
        componentName: "Loop Iterator 0"
        concurrency: "Sequential"
        variableToIterate: "EV_YEAR"
        startingValue: "16"
        incrementValue: "1"
        endValue: "18"
        breakOnFailure: "No"
    S3 Load 0:
      type: "s3-load"
      skipped: false
      parameters:
        componentName: "S3 Load 0"
        stage: "S3prjrenbanking_SnowMY_BANKING"
        pattern: "${EV_BANK_TRANS_DIRECTORY}/trnx_${EV_YEAR}.csv"
        encryption: "None"
        warehouse: "COMPUTE_WH"
        database: "DEMO_DB"
        schema: "MY_BANKING"
        targetTable: "TXNS_${EV_YEAR}"
        loadColumns:
        format: "[Custom]"
        fileType: "CSV"
        compression: "AUTO"
        recordDelimiter: ""
        fieldDelimiter: ","
        skipHeader: "1"
        skipBlankLines: "False"
        dateFormat: ""
        timeFormat: ""
        timestampFormat: ""
        escape: ""
        escapeUnenclosedField: ""
        trimSpace: "False"
        fieldOptionallyEnclosed: ""
        nullIf:
        errorOnColumnCountMismatch: "False"
        emptyFieldAsNull: "True"
        replaceInvalidCharacters: "False"
        encodingType: ""
        onError: "Abort Statement"
        sizeLimitB: ""
        purgeFiles: "False"
        truncateColumns: "False"
        forceLoad: "True"
        metadataFields:
    Loop Iterator 1:
      type: "loop-iterator"
      iterationTarget: "S3 Load 0"
      skipped: false
      parameters:
        componentName: "Loop Iterator 1"
        concurrency: "Sequential"
        variableToIterate: "EV_YEAR"
        startingValue: "16"
        incrementValue: "1"
        endValue: "18"
        breakOnFailure: "No"
design:
  components:
    Start 0:
      position:
        x: -688
        "y": 112
      tempMetlId: 7607
    SQL Script 0:
      position:
        x: -448
        "y": 96
      tempMetlId: 7608
    Loop Iterator 0:
      position:
        x: -448
        "y": 96
      tempMetlId: 7609
    S3 Load 0:
      position:
        x: -304
        "y": 144
      tempMetlId: 7692
    Loop Iterator 1:
      position:
        x: -304
        "y": 112
      tempMetlId: 7848
